#!/bin/bash

SCRIPT=akira-decrypted.tcl

if [ ! -z "$1" ]; then
	SCRIPT=$1
fi

cat > $SCRIPT.html << EOF
<!DOCTYPE html>
<html lang='en'>

<head>
	<meta charset='utf-8' />
	<meta http-equiv='X-UA-Compatible' content='IE=edge' />
	<meta name='viewport' content='width=device-width, initial-scale=1.0' />
	<title>nagelfar - $SCRIPT</title>
</head>

<body style="background-color:#000;color:#e1e1e1;font-size:12pt">
<pre>
EOF
nagelfar -quiet -tab 4 -html -Welse0 -prefix l $SCRIPT >> $SCRIPT.html
cat >> $SCRIPT.html <<EOF
</pre>
</body>

</html>
EOF

# vim: ft=sh ts=4 sw=4 noet:
